// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joovupvjegfnjgkyxekf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvb3Z1cHZqZWdmbmpna3l4ZWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjk0MTYsImV4cCI6MjA3MDcwNTQxNn0.nTvkfT4wJOuSm0LUyrrFGR2xXM6A0-5ManYo31mg9Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});